Refactor velocity representations as integers
ami-iit/jaxsim pull request #160
Opened 2024-05-23 10:27 UTC by flferretti

This pull request refactors the velocity representation in the JaxSim API. The changes include avoiding the use of `enum` in `VelRepr` and making `velocity_representation` a non-static argument in some methods of `jaxsim.api.JaxSimModelData`. These changes improve the compatibility with JAX while avoiding breaking changes in the API

2024-06-10 20:30 UTC, flferretti commented
The AD tests take a bit longer to complete. This can be due to the JAX traceback used in `JaxSimModelReferences` that can lead to this effect when trying to compute the gradients

2024-06-11 07:55 UTC, diegoferigo commented
Awesome, thanks @flferretti for this PR. I'd expect the following consequences of this PR:

- With static velocity representations, functions compiled passing different values are for JAX different. Only the section of the removed match-case statement is included in the compiled IR.
- I expect now a slightly slower compilation of our functions since they include more code, but in most cases the match-case statements only contain a bunch of transforms computation, nothing too heavy. `TL;DR` slower JIT compilations for a single call, but no recompilations in case multiple representations are needed.
- I expect, however, a smaller "equivalent binary" size of a large jit-compiled application. In fact, it happens to call the same JIT-compiled function with different representations (sometimes making calculation e.g. in body-fixed is easier even if the active representation is different), therefore before the full binary might have contained multiple copies of the same RBDA where the only difference was the match-case entry used to adjust the representation. `TL;DR` better memory footprint.

Not yet sure if my intuition is correct.

This being said, I'd like to tag a release with all the previous improvement. I don't expect surprises here, but being such a large change touching pretty much all our API surface, I prefer being cautious and include this PR in the following release (v0.4.0). I'll be reviewing this shortly.

2024-06-11 07:57 UTC, diegoferigo commented
> The AD tests take a bit longer to complete.

I guess that now AD needs to propagate gradients through all possible branches instead of just one. And yes, this might take longer.

2024-06-11 08:01 UTC, flferretti commented
I agree with your intuitions, the IR should now include the three branches for each velocity representation and the recompilation should not be triggered when we use `switch_velocity_representation` or `from_other_to_inertial` or `from_inertial_to_other`.

>  I'd like to tag a release with all the previous improvement. I don't expect surprises here, but being such a large change touching pretty much all our API surface, I prefer being cautious and include this PR in the following release (v0.4.0). I'll be reviewing this shortly.

I totally agree, this can be potentially disruptive, so I'd also prefer to be cautious and eventually rebase this onto #172

2024-06-14 07:47 UTC, diegoferigo requested changes
I've just finished a first review pass, things look generally good. I'll going to request some changes, and make a second pass later. I still need to weight some consequences especially on AD performance.

Here below my comments / questions:

- Most of the match-case seem to me 1:1 with the new lax.switch functions. Are there any sections in which you had to modify the original code? I checked the diff, but since it's quite large, I could have missed something. 
- In most cases, this PR does not alter significantly the readability of the code, I like that. We already had an extra indentation level due to the match-case statements, and the new functions use the same. There are cases, however, where the logic got much more complex and indented, like in `JaxSimModelReferences`. Let's keep this in mind in case we want to refactor it with a more simple approach.
- Do you think it could be helpful adding a new `jaxsim.typing.VelRepr` variable that points to `int`? Since this removed enum are part of the core public APIs, I'd prefer to make clear that those are not generic integer types.

2024-06-14 08:13 UTC, flferretti commented on src/jaxsim/api/references.py
> +                model=model, data=data or JaxSimModelData.zero(model=model)
The logic should fail before, but since both branches are compiled, JAX was complaining that `data` was None

2024-06-14 13:29 UTC, flferretti commented
> Most of the match-case seem to me 1:1 with the new lax.switch functions. Are there any sections in which you had to modify the original code? I checked the diff, but since it's quite large, I could have missed something.

No, they should be equivalent

> In most cases, this PR does not alter significantly the readability of the code, I like that. We already had an extra indentation level due to the match-case statements, and the new functions use the same. There are cases, however, where the logic got much more complex and indented, like in `JaxSimModelReferences`. Let's keep this in mind in case we want to refactor it with a more simple approach.

Yes, the logic got more complex since I needed to somehow check the values of some parameters. We can think of a smarter solution to handle that in the future.

> Do you think it could be helpful adding a new jaxsim.typing.VelRepr variable that points to int? Since this removed enum are part of the core public APIs, I'd prefer to make clear that those are not generic integer types.

Totally yes! I'll a commit for that

2024-06-14 16:20 UTC, flferretti commented on src/jaxsim/api/references.py
> +            )
Done in https://github.com/ami-iit/jaxsim/pull/160/commits/432ec2c63f2f7d99d4d71d887f31c27a05689cbb

2024-06-14 16:20 UTC, flferretti commented on src/jaxsim/api/references.py
> +                model=model, data=data or JaxSimModelData.zero(model=model)
Check https://github.com/ami-iit/jaxsim/pull/160/commits/432ec2c63f2f7d99d4d71d887f31c27a05689cbb

2024-06-14 16:21 UTC, flferretti commented on src/jaxsim/api/references.py
> +            )
I'll leave this unresolved

2024-06-14 16:32 UTC, diegoferigo commented on src/jaxsim/api/references.py
> +            )
Got back on this in https://github.com/ami-iit/jaxsim/pull/181.

2024-07-19 12:38 UTC, flferretti commented
I'll rebase this right before the next release @diegoferigo

2024-08-27 15:27 UTC, flferretti commented
Checks are failing due to a timeout of the CI

2025-05-15 09:35 UTC, flferretti commented
Closing without merging as this won't bring any significant performance/feature improvement

2025-05-15 09:35 UTC, closed without merging