Add frame example
ami-iit/jaxsim pull request #300
Opened 2024-11-26 17:23 UTC by CarlottaSartore

This PR adds  the example for computing velocity and transformation of the frames. In addition, it introduces minor changes to align the frames API with the link's one 

----
📚 Documentation preview 📚: https://jaxsim--300.org.readthedocs.build//300/

2024-11-26 18:30 UTC, xela-95 requested changes
Thanks @CarlottaSartore for your contribution! I just left some minor comments. 

Other than this, would you add a little unit test on the `jaxsim.api.frame.velocity` function to avoid regressions in future? It can be added to https://github.com/ami-iit/jaxsim/blob/main/tests/test_api_frame.py

2024-11-26 18:30 UTC, xela-95 commented on src/jaxsim/api/frame.py
> +    O_J_WL_I = jacobian(
```suggestion
    # Get the frame jacobian having I as input representation (taken from data)
    # and O as output representation, specified by the user (or taken from data).
    O_J_WF_I = jacobian(
```

2024-11-26 18:30 UTC, xela-95 commented on src/jaxsim/api/frame.py
> +    return O_J_WL_I @ I_ν
```suggestion
    # Compute the frame velocity in the output velocity representation.
    return O_J_WF_I @ I_ν
```

2024-11-27 09:36 UTC, CarlottaSartore commented
> Thanks @CarlottaSartore for your contribution! I just left some minor comments.
> 
> Other than this, would you add a little unit test on the `jaxsim.api.frame.velocity` function to avoid regressions in future? It can be added to https://github.com/ami-iit/jaxsim/blob/main/tests/test_api_frame.py

Thanks @xela-95, I have implemented the CI in 5fdbe5b37dc7374ba0bf0600e23fa82abacf13a3

Let me know if there ar any additional changes needed !

2024-11-27 10:09 UTC, CarlottaSartore commented
I shoudl have fix with commit 436fde6c3444d9088c09abae5e22876d5eba78b6

The error was that Jaxsim creates a single vector organise as : $[l_0, ..., l_{nl}, f_0,..., f_{nf}]$
What happens is that the idx returned by frame `name_to_idx` is the idx inside such vector and not the index of the vector containing only frames. 
Thus such index should be $>nl$ and $<nl+nf$

2024-11-27 15:50 UTC, xela-95 commented
> The error was that Jaxsim creates a single vector organise as : [ l 0 , . . . , l n l , f 0 , . . . , f n f ] What happens is that the idx returned by frame `name_to_idx` is the idx inside such vector and not the index of the vector containing only frames. Thus such index should be > n l and < n l + n f

 Right nice catch!

2024-11-27 15:54 UTC, flferretti requested changes
Minor typo

2024-11-27 15:54 UTC, flferretti commented on src/jaxsim/api/frame.py
> +            The output velocity representation of the link velocity.
```suggestion
            The output velocity representation of the frame velocity.
```

2024-11-27 15:55 UTC, xela-95 approved these changes
Now it's good for me! :)

2024-11-28 16:24 UTC, CarlottaSartore commented
Thanks @xela-95, and @flferretti  I should have also implemented your review,  is it right ? can I proceed with the merge ?

2024-11-28 16:47 UTC, merged